name: flutter_folio
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  photo_view: ^0.15.0
  dio: ^5.0.3
  riverpod: ^2.3.2
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  build_runner: ^2.3.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  responsive_builder: ^0.7.0
  url_launcher: ^6.1.11
  path_provider_foundation: ^2.2.3
  scrollview_observer: ^1.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.1.4
  riverpod_lint: ^2.3.10

 
 
 
 
 
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4





flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/screenshots/
    - assets/images/logo/
    - assets/images/logo/programming/
    - assets/images/logo/project_apps/
    - assets/images/logo/social_media/


  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        
        - asset: assets/fonts/Zeyada-Regular.ttf
          style: italic
        
 
 
 

 
 

 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
