name: flutter_folio
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
 
 
 
 
  flutter_lints: ^2.0.0





flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        
        - asset: assets/fonts/Zeyada-Regular.ttf
          style: italic
        
 
 
 

 
 

 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
