name: Build and Deploy

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'  # Specify the version you need

    - name: Build Release
      run: |
        flutter --version
        flutter build web

    - name: Deploy to Another Repo
      env:
        TARGET_REPO:  BabishShrestha/babishshrestha.github.io  # Replace with your target repo
        TARGET_BRANCH: main  # The branch you want to deploy to in the target repo
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Your GitHub token
      run: |
        # Configure Git
        git config --global user.name 'Babish Shrestha'
        git config --global user.email 'babishshrestha8@gmail.com'

        # Clone the target repository and switch to the target branch
        git clone https://$PERSONAL_TOKEN@github.com/$TARGET_REPO.git deploy_repo
        cd deploy_repo
        git checkout $TARGET_BRANCH || git checkout -b $TARGET_BRANCH

        # Sync the built web files to the cloned repo
        rsync -av --delete ../build/web/ .

        # Commit and push changes
        git add .
        git commit -m "Deploy new release"
        git push origin $TARGET_BRANCH
